apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-tracker
  labels:
    app: fleetman-position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-tracker
  template:
    metadata:
      labels:
        app: fleetman-position-tracker
    spec:
      containers:
        - name: position-tracker
          image: supinfo4kube/position-tracker:1.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production-microservice"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  mongo --host fleetman-mongodb --port 27017 --eval "db.runCommand('ping')" || exit 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
