apiVersion: v1
kind: Service
metadata:
  name: fleetman-web-app
  labels:
    app: fleetman-web-app
spec:
  selector:
    app: fleetman-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
