apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg== # Base64 de "mongoadmin"
  mongo-root-password: bW9uZ29wYXNz # Base64 de "mongopass"
