apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
  labels:
    app: fleetman-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongodb
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.23
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.runCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5

      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
