apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
spec:
  selector:
    app: fleetman-queue
  ports:
    - name: messaging
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: admin
      protocol: TCP
      port: 8161
      targetPort: 8161
  type: ClusterIP
